# Generated by Django 4.2 on 2023-05-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_post_body_alter_post_image_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубліковане'),
        ),
    ]
