# Generated by Django 4.2 on 2023-05-09 18:07

import base.models
import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_post_date_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.image_user_directory_path, validators=[base.validators.validate_file_size], verbose_name='Фон профілю'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опублікувати'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Ім'я профілю"),
        ),
    ]
