# Generated by Django 4.2 on 2023-05-02 17:50

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroupmessage',
            options={},
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='image',
            field=models.ImageField(blank=True, default='default_chatgroup.png', upload_to='images/groups', validators=[chat.models.ChatGroup.validate_image]),
        ),
    ]
