# Generated by Django 4.2 on 2023-05-08 15:38

import base.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='description',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='image',
            field=models.ImageField(blank=True, default='default_chatgroup.png', upload_to='images/groups', validators=[base.validators.validate_file_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Учасники'),
        ),
    ]
