# Generated by Django 4.2 on 2023-05-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatgroupmessage_options_alter_chatgroup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
