# Generated by Django 4.2 on 2023-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_bio_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_user.png', null=True, upload_to='images/profile'),
        ),
    ]
