# Generated by Django 4.2 on 2023-05-07 13:59

import base.models
import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userfile_post_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='Тіло'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.post_user_directory_path, validators=[base.validators.validate_file_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Біографія'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_user.png', null=True, upload_to=base.models.image_user_directory_path, validators=[base.validators.validate_file_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=base.models.user_directory_path, validators=[base.validators.validate_file_size], verbose_name='Файл'),
        ),
    ]
