# Generated by Django 4.2 on 2023-05-02 17:50

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_post_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post', validators=[base.models.Post.validate_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_user.png', null=True, upload_to='images/profile', validators=[base.models.User.validate_image]),
        ),
    ]
