# Generated by Django 4.2 on 2023-05-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_post_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
