# Generated by Django 4.2 on 2023-05-08 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='arhived',
            field=models.BooleanField(default=False, verbose_name='Архівовано'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_archive',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архівації'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_pinned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата й час закріплення'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_unpinned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата й час відкріплення'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Перевірено'),
        ),
    ]
