# Generated by Django 4.2 on 2023-05-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_arhived_post_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_pinned',
        ),
    ]
