# Generated by Django 4.2 on 2023-05-06 11:37

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to='images/profile', validators=[base.models.User.validate_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Студент'), (2, 'Викладач')], default=1),
        ),
    ]
