# Generated by Django 4.2.1 on 2023-05-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_review_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='review_topics',
            field=models.ManyToManyField(blank=True, related_name='review_topics', to='base.posttopic', verbose_name='Теми перевірки'),
        ),
    ]
