# Generated by Django 4.2.10 on 2024-02-13 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import studentflow.base.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default_chatgroup.png', upload_to='images/groups', validators=[studentflow.base.validators.validate_file_size], verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='Опис')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('private', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Учасники')),
            ],
        ),
        migrations.CreateModel(
            name='ChatGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatgroup')),
            ],
        ),
    ]
